apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: food-delivery
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/version: "1.0.0"
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
